// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cipgzfvvctekljfprezz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpcGd6ZnZ2Y3Rla2xqZnByZXp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMjI4MDUsImV4cCI6MjA2MTY5ODgwNX0.IRa362fHbqACD4VExH1d4Coj7gNonFTvv-AWHGHaFzU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);